version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  check:
    cmds:
      - task: ecma:mono-check

  fix:
    cmds:
      - task: ecma:mono-fix
      - pnpm exec mono-langtool src/strings --no-confirm

  edit:
    desc: Make edits to the translation files
    cmds:
      - pnpm exec mono-langtool src/strings {{.CLI_ARGS}}

  git-push:
    cmds:
      - git remote set-url origin git@github.com:Pistonight/shared-controls
      - git push
