version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  check:
    cmds:
      - task: ecma:mono-check

  fix:
    cmds:
      - task: ecma:mono-fix

  git-push:
    cmds:
      - git remote set-url origin git@github.com:Pistonight/shared-controls
      - git push
